# Generated by Django 5.0.6 on 2024-05-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
